### ISSUE TITLE
Avoid using unconditional PUT

### ISSUE THREAD

**Issue by michielbdejong** [Otto-AA/solid-acl-utils#1]
Great library, thanks for developing this! Small remark: It seems to do an unconditional PUT in https://github.com/Otto-AA/solid-acl-utils/blob/master/src/AclApi.ts#L61 which is not best practice. To avoid overwriting updates from other clients, you could either use an `If-Match` header (so if two concurrent requests happen, one of them will be cancelled) or a PATCH verb (so if two concurrent requests happen, both will succeed, although that may be hard to reason about).

**Comment by Otto-AA** [comment]
Thanks for your comment. I've never used the If-Match header, but I will read a bit about it and then use it.

If I understood it correctly, this is for the scenario that I read the acl file, another app modifies it, and then I want to update it. Is this what you mean?

**Comment by Otto-AA** [comment]
I've added an `If-Match` check to the saveDoc method. Could you take a look at the PR (#2 ) and tell me if this is what you meant?
It's not easy to test, because NSS support for etags and if-match is currently not available (weak etags -> if-match gets ignored; etags not provided on GET requests; if-match maybe completely ignored by NSS), so feedback from you would be very welcome :)
